

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

-- Name: public; Type: SCHEMA; Schema: -; Owner: pg_database_owner

CREATE SCHEMA public;


ALTER SCHEMA public OWNER TO pg_database_owner;


-- Name: SCHEMA public; Type: COMMENT; Schema: -; Owner: pg_database_owner

COMMENT ON SCHEMA public IS 'standard public schema';


SET default_tablespace = '';

SET default_table_access_method = heap;


-- Name: projects; Type: TABLE; Schema: public; Owner: postgres

CREATE TABLE public.projects (
    start_date date,
    created_at timestamp(6) without time zone,
    id bigint NOT NULL,
    name character varying(100) NOT NULL,
    description text
);


ALTER TABLE public.projects OWNER TO postgres;


-- Name: projects_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres

ALTER TABLE public.projects ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.projects_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


-- Name: tasks; Type: TABLE; Schema: public; Owner: postgres

CREATE TABLE public.tasks (
    date_of_birth date,
    created_at timestamp(6) without time zone,
    id bigint NOT NULL,
    project_id bigint NOT NULL,
    code_number character varying(20),
    status character varying(50) NOT NULL,
    first_name character varying(100),
    last_name character varying(100),
    title character varying(200) NOT NULL,
    description text
);


ALTER TABLE public.tasks OWNER TO postgres;

-- Name: tasks_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres

ALTER TABLE public.tasks ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tasks_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


-- Name: users; Type: TABLE; Schema: public; Owner: postgres


CREATE TABLE public.users (
    id bigint NOT NULL,
    role character varying(20),
    username character varying(50) NOT NULL,
    password character varying(255) NOT NULL
);


ALTER TABLE public.users OWNER TO postgres;

-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


-- Name: projects projects_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres

ALTER TABLE ONLY public.projects
    ADD CONSTRAINT projects_name_key UNIQUE (name);


-- Name: projects projects_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres

ALTER TABLE ONLY public.projects
    ADD CONSTRAINT projects_pkey PRIMARY KEY (id);


-- Name: tasks tasks_code_number_key; Type: CONSTRAINT; Schema: public; Owner: postgres

ALTER TABLE ONLY public.tasks
    ADD CONSTRAINT tasks_code_number_key UNIQUE (code_number);


-- Name: tasks tasks_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres

ALTER TABLE ONLY public.tasks
    ADD CONSTRAINT tasks_pkey PRIMARY KEY (id);

-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);

-- Name: users users_username_key; Type: CONSTRAINT; Schema: public; Owner: postgres

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_username_key UNIQUE (username);


-- Name: tasks fksfhn82y57i3k9uxww1s007acc; Type: FK CONSTRAINT; Schema: public; Owner: postgres

ALTER TABLE ONLY public.tasks
    ADD CONSTRAINT fksfhn82y57i3k9uxww1s007acc FOREIGN KEY (project_id) REFERENCES public.projects(id);

