

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

-- Name: public; Type: SCHEMA; Schema: -; Owner: pg_database_owner

CREATE SCHEMA public;


ALTER SCHEMA public OWNER TO pg_database_owner;


-- Name: SCHEMA public; Type: COMMENT; Schema: -; Owner: pg_database_owner

COMMENT ON SCHEMA public IS 'standard public schema';


SET default_tablespace = '';

SET default_table_access_method = heap;


-- Name: projects; Type: TABLE; Schema: public; Owner: postgres

CREATE TABLE public.projects (
    created_at timestamp(6) without time zone,
    id bigint NOT NULL,
    name character varying(100) NOT NULL,
    description text
);


ALTER TABLE public.projects OWNER TO postgres;


-- Name: projects_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres

ALTER TABLE public.projects ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.projects_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


-- Name: students; Type: TABLE; Schema: public; Owner: postgres

CREATE TABLE public.students (
    date_of_birth date,
    created_at timestamp(6) without time zone,
    id bigint NOT NULL,
    project_id bigint NOT NULL,
    code_number character varying(20) NOT NULL,
    first_name character varying(100) NOT NULL,
    last_name character varying(100) NOT NULL,
    title character varying(200) NOT NULL,
    description text
);


ALTER TABLE public.students OWNER TO postgres;

-- Name: students_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres

ALTER TABLE public.students ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.students_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


-- Name: users; Type: TABLE; Schema: public; Owner: postgres


CREATE TABLE public.users (
    id bigint NOT NULL,
    role character varying(20),
    username character varying(50) NOT NULL,
    password character varying(255) NOT NULL
);


ALTER TABLE public.users OWNER TO postgres;

-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


-- Name: projects projects_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres

ALTER TABLE ONLY public.projects
    ADD CONSTRAINT projects_name_key UNIQUE (name);


-- Name: projects projects_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres

ALTER TABLE ONLY public.projects
    ADD CONSTRAINT projects_pkey PRIMARY KEY (id);


-- Name: students students_code_number_key; Type: CONSTRAINT; Schema: public; Owner: postgres

ALTER TABLE ONLY public.students
    ADD CONSTRAINT students_code_number_key UNIQUE (code_number);


-- Name: students uk_student_name; Type: CONSTRAINT; Schema: public; Owner: postgres

ALTER TABLE ONLY public.students
    ADD CONSTRAINT uk_student_name UNIQUE (first_name, last_name);


-- Name: students students_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres

ALTER TABLE ONLY public.students
    ADD CONSTRAINT students_pkey PRIMARY KEY (id);

-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);

-- Name: users users_username_key; Type: CONSTRAINT; Schema: public; Owner: postgres

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_username_key UNIQUE (username);


-- Name: students fk_students_project; Type: FK CONSTRAINT; Schema: public; Owner: postgres

ALTER TABLE ONLY public.students
    ADD CONSTRAINT fk_students_project FOREIGN KEY (project_id) REFERENCES public.projects(id) ON DELETE CASCADE;


-- Name: idx_students_project_id; Type: INDEX; Schema: public; Owner: postgres

CREATE INDEX idx_students_project_id ON public.students(project_id);


-- Name: idx_students_created_at; Type: INDEX; Schema: public; Owner: postgres

CREATE INDEX idx_students_created_at ON public.students(created_at);


-- Name: idx_projects_created_at; Type: INDEX; Schema: public; Owner: postgres

CREATE INDEX idx_projects_created_at ON public.projects(created_at);


-- Name: check_role; Type: CHECK CONSTRAINT; Schema: public; Owner: postgres

ALTER TABLE public.users ADD CONSTRAINT check_role CHECK (role IN ('USER', 'ADMIN'));
